config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  root 'pages#index'

  # Accounts
  resources :accounts, param: :aid

  # Posts
  resources :posts, param: :aid

  # Images
  resources :images, param: :aid do
    member do
      post "create_variant" => "images#create_variant", as: "create_variant"
      delete "delete_variant" => "images#delete_variant", as: "delete_variant"
      delete "delete_original" => "images#delete_original", as: "delete_original"
    end
  end

  # Videos
  resources :videos, param: :aid do
    member do
      post "create_variant" => "videos#create_variant", as: "create_variant"
      delete "delete_variant" => "videos#delete_variant", as: "delete_variant"
      delete "delete_original" => "videos#delete_original", as: "delete_original"
    end
  end

  # Emojis
  resources :emojis, param: :aid do
    collection do
      get :picker
    end
  end

  # Reactions
  post 'reactions/react' => 'reactions#react', as: :react

  # Diffuses
  post 'diffuses/create' => 'diffuses#create', as: :diffuse
  delete 'diffuses/destroy' => 'diffuses#destroy', as: :undiffuse

  # Sessions
  get 'sessions/start'
  delete 'signout' => 'sessions#signout'
  resources :sessions, except: [:new, :create], param: :aid

  # Signup
  get 'signup' => 'signup#new'
  post 'signup' => 'signup#create'

  # OAuth
  post 'oauth/start' => 'oauth#start'
  get 'oauth/callback' => 'oauth#callback'
  post 'oauth/fetch' => 'oauth#fetch'

  # Trends
  resources :trends, only: [:index, :create]

  # Notifications
  resources :notifications, only: [:new, :create]

  # OG
  get 'og/posts/:aid' => 'og_images#post', as: :og_post
  # get 'og/accounts/:aid' => 'og_images#account', as: :og_account

  # API v1
  namespace :v1 do
    root 'pages#index'

    # Pages
    get 'start' => 'pages#start'

    # Accounts
    post 'accounts/@:name_id' => 'accounts#show', constraints: { name_id: /.*/ }
    resources :accounts, only: [], param: :aid do
      resource :follow, only: [:create, :destroy]
    end

    # Posts
    post 'posts/:aid' => 'posts#show'
    resources :posts, only: [:create, :destroy], param: :aid do
      resource :reaction, only: [:create, :destroy]
      resource :diffuse, only: [:create, :destroy]
      post 'quotes'
      post 'diffusions'
      post 'reactions'
    end

    # Emojis
    post 'emojis/groups' => 'emojis#groups_index'
    post 'emojis/groups/:group_name' => 'emojis#groups_show'
    post 'emojis/:name_id' => 'emojis#show'

    # Search
    post 'search' => 'search#index'

    # Feeds
    post 'feeds/index' => 'feeds#index'
    post 'feeds/follow' => 'feeds#follow'
    post 'feeds/current' => 'feeds#current'
    post 'feeds/account' => 'feeds#account'

    # Notifications
    post 'notifications' => 'notifications#index'
    post 'notifications/unread_count' => 'notifications#unread_count'

    # WebPush Subscriptions
    post 'webpush_subscriptions' => 'webpush_subscriptions#create'

    # Sessions
    post 'sessions/create' => 'sessions#create'
    delete 'signout' => 'sessions#signout'

    # Signup
    post 'signup' => 'signup#create'

    # Settings
    post 'settings/account' => 'settings#account'
    post 'settings/notification' => 'settings#notification'
    post 'settings/update_notification' => 'settings#update_notification'
    delete 'settings/leave' => 'settings#leave'

    # OAuth
    post 'oauth/start' => 'oauth#start'
    post 'oauth/callback' => 'oauth#callback'
    post 'oauth/fetch' => 'oauth#fetch'

    # Trends
    post 'trends' => 'trends#index'
  end

  # Others
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Errors
  match '*path', to: 'application#routing_error', via: :all
end

app/models/video.rb
class Video < ApplicationRecord
  include VideoProcessable

  belongs_to :account, optional: true
  has_many :post_videos

  attribute :variants, :json, default: -> { [] }
  attribute :meta, :json, default: -> { {} }
  enum :visibility, { opened: 0, limited: 1, closed: 2 }, default: :opened
  enum :status, { normal: 0, locked: 1, deleted: 2 }
  attr_accessor :video

  after_initialize :set_aid, if: :new_record?
  before_create :video_upload
  after_create_commit :enqueue_processing

  validates :name,
    allow_blank: true,
    length: { in: 1..50 }
  validates :description,
    allow_blank: true,
    length: { in: 1..500 }
  validate :video_validation

  scope :from_normal_account, -> { left_joins(:account).where(accounts: { status: :normal }) }
  scope :is_normal, -> { where(status: :normal) }
  scope :isnt_deleted, -> { where.not(status: :deleted) }
  scope :is_opened, -> { where(visibility: :opened) }
  scope :isnt_closed, -> { where.not(visibility: :closed) }

  def video_url
    if normal? && variant_type.present?
      object_url(key: "/videos/variants/#{aid}.mp4")
    elsif normal?
      full_url('/static_assets/videos/loading.mp4')
    else
      full_url('/static_assets/videos/amiverse-1.mp4')
    end
  end

  def create_variant(next_variant_type = 'normal')
    return false if original_ext.blank?
    VideoProcessingJob.perform_later(id, next_variant_type)
  end

  def delete_variant
    s3_delete(key: "/videos/variants/#{aid}.mp4")
    self.variant_type = nil
    save
  end

  def delete_original
    s3_delete(key: "/videos/originals/#{aid}.#{original_ext}")
    self.original_ext = nil
    save
  end

  private

  def enqueue_processing
    VideoProcessingJob.perform_later(id)
  end

  def video_upload
    self.name = video.original_filename.split('.').first if name.blank?
    extension = video.original_filename.split('.').last.downcase
    self.original_ext = extension

    s3_upload(
      key: "/videos/originals/#{aid}.#{extension}",
      file: video.path,
      content_type: video.content_type
    )

    # processed_file = video.process_video(input_path: video.path, video: self, variant_type: 'copy')
    # s3_upload(
    #   key: "/videos/variants/#{aid}.mp4",
    #   file: processed_file.path,
    #   content_type: 'video/mp4'
    # )
  end

  def video_validation
    return unless new_record?

    if video.blank?
      errors.add(:video, :blank)
      return
    end

    if video.size > 500.megabytes
      errors.add(:video, 'must be 500MB or less')
    end

    allowed_types = %w[video/mp4 video/quicktime video/x-msvideo video/x-matroska video/webm]
    unless allowed_types.include?(video.content_type)
      errors.add(:video, 'must be a supported video format (mp4, mov, avi, mkv, webm)')
    end

    begin
      movie = FFMPEG::Movie.new(video.path)
      if movie.duration < 3
        errors.add(:video, 'must be at least 3 seconds')
      elsif movie.duration > 5.minutes
        errors.add(:video, 'must be 5 minutes or less')
      end
    rescue StandardError
      errors.add(:video, 'could not be processed')
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_video, only: %i[show]
  before_action :set_correct_video, only: %i[edit update destroy create_variant delete_variant delete_original]

  def index
    videos = Video.all.order(id: :desc)
    @videos = set_pagination_for(videos)
  end

  def show; end

  def new
    @video = Video.new
  end

  def edit; end

  def create
    @video = Video.new(video_params)
    @video.account = @current_account
    if @video.save
      redirect_to videos_path, notice: '作成しました'
    else
      flash.now[:alert] = '作成できませんでした'
      render :new
    end
  end

  def update
    if @video.update(video_params)
      redirect_to video_path(@video.aid), notice: '更新しました'
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    if @video.update(status: :deleted)
      redirect_to videos_path, notice: '削除しました'
    else
      flash.now[:alert] = '削除できませんでした'
      render :edit
    end
  end

  def create_variant
    if @video.create_variant(params[:variant_type])
      redirect_to video_path(@video.aid), notice: '動画を生成しました'
    else
      flash.now[:alert] = '動画を生成できませんでした'
      render :show
    end
  end

  def delete_variant
    if @video.delete_variant
      redirect_to video_path(@video.aid), notice: 'variantを削除しました'
    else
      flash.now[:alert] = 'variantを削除できませんでした'
      render :show
    end
  end

  def delete_original
    if @video.delete_original
      redirect_to video_path(@video.aid), notice: 'originalを削除しました'
    else
      flash.now[:alert] = 'originalを削除できませんでした'
      render :show
    end
  end

  private

  def video_params
    params.expect(
      video: [
        :name,
        :description,
        :visibility,
        :status
      ]
    )
  end

  def set_video
    @video = Video.is_normal.isnt_closed.find_by(aid: params[:aid])
    return if @video

    @video = Video.unscoped.find_by(aid: params[:aid])
    return if admin? && @video

    render_404
  end

  def set_correct_video
    return render_404 unless @current_account

    @video = @current_account.videos.is_normal.find_by(aid: params[:aid])
    return if @video

    @video = Video.unscoped.find_by(aid: params[:aid])
    return if admin? && @video
    render_404
  end
end

app/views/videos/_form.html.erb
<%= form_with model: @video, url: url, data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', instead: @video %>
  <div>
    <%= f.label :video, 'video' %>
    <%= f.file_field :video %>
  </div>

  <div>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, placeholder: '名前' %>
  </div>

  <div>
    <%= f.label :visibility %>
    <%= f.select :visibility, Image.visibilities.keys.map { |k| [t("activerecord.enums.image.visibility.#{k}"), k] }, {} %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, Image.statuses.keys.map { |k| [t("activerecord.enums.image.status.#{k}"), k] }, {} %>
  </div>
  <br/>
  <br/>
  <%= f.submit '送信' %>
<% end %>

app/views/videos/_video.html.erb
<div>
  <strong>ID:</strong> <%= video.aid %><br />
  <strong>動画名:</strong> <%= video.name %><br />
  <strong>公開状態:</strong> <%= video.visibility %><br />
  <strong>状態:</strong> <%= video.status %><br />
  <strong>variant_type:</strong>
    <%= video.variant_type.present? ? 'あり: ' + video.variant_type : 'なし' %>
    <%= button_to('削除', delete_variant_video_path(video.aid), method: :delete, data: { turbo: false }) %>
  <strong>original_ext:</strong>
    <%= video.original_ext.present? ? 'あり: ' + video.original_ext : 'なし' %>
    <%= button_to('削除', delete_original_video_path(video.aid), method: :delete, data: { turbo: false }) %>
  <strong>操作:</strong>
  <%= form_with url: create_variant_video_path(video.aid), method: :post, data: { turbo: false } do %>
    <div>
      <%= label_tag :variant_type, "variant_type" %>
      <%= select_tag :variant_type, options_for_select(['normal', 'copy']) %>
    </div>
    <div>
      <%= submit_tag "送信" %>
    </div>
  <% end %>
  <%= link_to('見る', video_path(video.aid)) %>
  <%= link_to('編集', edit_video_path(video.aid)) %>
  <br />
  <%= video_tag(video.video_url, alt: "#{video.name}", style: 'width: 140px;', controls: true) %>
  <hr />
</div>

app/views/videos/edit.html.erb
<% provide(:title, '編集') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<%= render 'videos/form', video: @video, url: video_path(@video.aid), method: :post, new: true %>

app/views/videos/index.html.erb
<% provide(:title, '動画一覧') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<h1>動画一覧</h1>
<%= render partial: 'videos/video', collection: @videos, as: 'video' %>
<%= render 'shared/paging', pages: @total_pages, page: @page, page_to: '/videos' %>

app/views/videos/new.html.erb
<% provide(:title, '作成') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<%= render 'videos/form', video: @video, url: videos_path, method: :post, new: true %>

app/views/videos/show.html.erb
<% provide(:title, '動画を見る') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<h1>動画</h1>
<%= video_tag(@video.video_url, alt: "#{@video.name}", controls: true) %>
<hr />
<%= render 'videos/video', video: @video %>