config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  root 'pages#index'

  # Accounts
  resources :accounts, param: :aid

  # Posts
  resources :posts, param: :aid

  # Images
  resources :images, param: :aid do
    member do
      post "create_variant" => "images#create_variant", as: "create_variant"
      delete "delete_variant" => "images#delete_variant", as: "delete_variant"
      delete "delete_original" => "images#delete_original", as: "delete_original"
    end
  end

  # Videos
  resources :videos, param: :aid do
    member do
      post "create_variant" => "videos#create_variant", as: "create_variant"
      delete "delete_variant" => "videos#delete_variant", as: "delete_variant"
      delete "delete_original" => "videos#delete_original", as: "delete_original"
    end
  end

  # Emojis
  resources :emojis, param: :aid do
    collection do
      get :picker
    end
  end

  # Reactions
  post 'reactions/react' => 'reactions#react', as: :react

  # Diffuses
  post 'diffuses/create' => 'diffuses#create', as: :diffuse
  delete 'diffuses/destroy' => 'diffuses#destroy', as: :undiffuse

  # Sessions
  get 'sessions/start'
  delete 'signout' => 'sessions#signout'
  resources :sessions, except: [:new, :create], param: :aid

  # Signup
  get 'signup' => 'signup#new'
  post 'signup' => 'signup#create'

  # OAuth
  post 'oauth/start' => 'oauth#start'
  get 'oauth/callback' => 'oauth#callback'
  post 'oauth/fetch' => 'oauth#fetch'

  # Trends
  resources :trends, only: [:index, :create]

  # Notifications
  resources :notifications, only: [:new, :create]

  # OG
  get 'og/posts/:aid' => 'og_images#post', as: :og_post
  # get 'og/accounts/:aid' => 'og_images#account', as: :og_account

  # API v1
  namespace :v1 do
    root 'pages#index'

    # Pages
    get 'start' => 'pages#start'

    # Accounts
    post 'accounts/@:name_id' => 'accounts#show', constraints: { name_id: /.*/ }
    resources :accounts, only: [], param: :aid do
      resource :follow, only: [:create, :destroy]
    end

    # Posts
    post 'posts/:aid' => 'posts#show'
    resources :posts, only: [:create, :destroy], param: :aid do
      resource :reaction, only: [:create, :destroy]
      resource :diffuse, only: [:create, :destroy]
      post 'quotes'
      post 'diffusions'
      post 'reactions'
    end

    # Emojis
    post 'emojis/groups' => 'emojis#groups_index'
    post 'emojis/groups/:group_name' => 'emojis#groups_show'
    post 'emojis/:name_id' => 'emojis#show'

    # Search
    post 'search' => 'search#index'

    # Feeds
    post 'feeds/index' => 'feeds#index'
    post 'feeds/follow' => 'feeds#follow'
    post 'feeds/current' => 'feeds#current'
    post 'feeds/account' => 'feeds#account'

    # Notifications
    post 'notifications' => 'notifications#index'
    post 'notifications/unread_count' => 'notifications#unread_count'

    # WebPush Subscriptions
    post 'webpush_subscriptions' => 'webpush_subscriptions#create'

    # Sessions
    post 'sessions/create' => 'sessions#create'
    delete 'signout' => 'sessions#signout'

    # Signup
    post 'signup' => 'signup#create'

    # Settings
    post 'settings/account' => 'settings#account'
    post 'settings/notification' => 'settings#notification'
    post 'settings/update_notification' => 'settings#update_notification'
    delete 'settings/leave' => 'settings#leave'

    # OAuth
    post 'oauth/start' => 'oauth#start'
    post 'oauth/callback' => 'oauth#callback'
    post 'oauth/fetch' => 'oauth#fetch'

    # Trends
    post 'trends' => 'trends#index'
  end

  # Others
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Errors
  match '*path', to: 'application#routing_error', via: :all
end

app/models/image.rb
class Image < ApplicationRecord
  include ImageProcessable

  belongs_to :account, optional: true
  has_many :post_images

  attribute :variants, :json, default: -> { [] }
  attribute :meta, :json, default: -> { {} }
  enum :visibility, { opened: 0, limited: 1, closed: 2 }, default: :opened
  enum :status, { normal: 0, locked: 1, deleted: 2 }
  attr_accessor :image, :save_original

  after_initialize :set_aid, if: :new_record?
  before_create :image_upload
  before_save :file_visibility_check

  validates :name,
    allow_blank: true,
    length: { in: 1..50 }
  validates :description,
    allow_blank: true,
    length: { in: 1..500 }

  scope :from_normal_account, -> { left_joins(:account).where(accounts: { status: :normal }) }
  scope :is_normal, -> { where(status: :normal) }
  scope :isnt_deleted, -> { where.not(status: :deleted) }
  scope :is_opened, -> { where(visibility: :opened) }
  scope :isnt_closed, -> { where.not(visibility: :closed) }

  def image_url
    if normal? && variant_type.present?
      object_url(key: "/images/variants/#{aid}.webp")
    else
      full_url('/static_assets/images/amiverse-1.webp')
    end
  end

  def image_upload
    validate_image(required: true)

    self.save_original = true
    if save_original
      self.original_ext = image.original_filename.split('.').last.downcase
      s3_upload(
        key: "/images/originals/#{aid}.#{original_ext}",
        file: image.path,
        content_type: image.content_type
      )
    end
    self.name = image.original_filename.split('.').first if name.blank?

    return if deleted?

    self.variant_type = 'normal' if variant_type.blank?
    processed = process_image(image: image, variant_type: variant_type)
    s3_upload(
      key: "/images/variants/#{aid}.webp",
      file: processed.path,
      content_type: 'image/webp'
    )
    processed.delete
  end

  def create_variant(next_variant_type = 'normal')
    return false if original_ext.blank?

    tempfile = Tempfile.new(['tempfile', ".#{original_ext}"])
    tempfile.binmode
    s3_download(
      key: "/images/originals/#{aid}.#{original_ext}",
      response_target: tempfile
    )

    processed = process_image(image: tempfile, variant_type: next_variant_type)
    s3_upload(
      key: "/images/variants/#{aid}.webp",
      file: processed.path,
      content_type: 'image/webp'
    )
    processed.delete
    tempfile.close
    tempfile.unlink

    self.variant_type = next_variant_type
    save
  end

  def delete_variant
    s3_delete(key: "/images/variants/#{aid}.webp")
    self.variant_type = nil
    save
  end

  def delete_original
    s3_delete(key: "/images/originals/#{aid}.#{original_ext}")
    self.original_ext = nil
    save
  end

  private

  def file_visibility_check
    return unless deleted?
    s3_delete(key: "/images/variants/#{aid}.webp")
    self.variant_type = nil
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_image, only: %i[show]
  before_action :set_correct_image, only: %i[edit update destroy create_variant delete_variant delete_original]

  def index
    images = Image.all.order(id: :desc)
    @images = set_pagination_for(images)
  end

  def show; end

  def new
    @image = Image.new
  end

  def edit; end

  def create
    @image = Image.new(image_params)
    @image.account = @current_account
    if @image.save
      redirect_to images_path, notice: '作成しました'
    else
      flash.now[:alert] = '作成できませんでした'
      render :new
    end
  end

  def update
    if @image.update(image_params)
      redirect_to image_path(@image.aid), notice: '更新しました'
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    if @image.update(status: :deleted)
      redirect_to images_path, notice: '削除しました'
    else
      flash.now[:alert] = '削除できませんでした'
      render :edit
    end
  end

  def create_variant
    if @image.create_variant(params[:variant_type])
      redirect_to image_path(@image.aid), notice: '画像を生成しました'
    else
      flash.now[:alert] = '画像を生成できませんでした'
      render :show
    end
  end

  def delete_variant
    if @image.delete_variant
      redirect_to image_path(@image.aid), notice: 'variantを削除しました'
    else
      flash.now[:alert] = 'variantを削除できませんでした'
      render :show
    end
  end

  def delete_original
    if @image.delete_original
      redirect_to image_path(@image.aid), notice: 'originalを削除しました'
    else
      flash.now[:alert] = 'originalを削除できませんでした'
      render :show
    end
  end

  private

  def image_params
    params.expect(
      image: [
        :name,
        :description,
        :visibility,
        :status
      ]
    )
  end

  def set_image
    @image = Image.is_normal.isnt_closed.find_by(aid: params[:aid])
    return if @image

    @image = Image.unscoped.find_by(aid: params[:aid])
    return if admin? && @image

    render_404
  end

  def set_correct_image
    return render_404 unless @current_account

    @image = @current_account.images.is_normal.find_by(aid: params[:aid])
    return if @image

    @image = Image.unscoped.find_by(aid: params[:aid])
    return if admin? && @image

    render_404
  end
end

app/views/images/_form.html.erb
<%= form_with model: @image, url: url, data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', instead: @image %>
  <div>
    <%= f.label :image, 'image' %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, placeholder: '名前' %>
  </div>

  <div>
    <%= f.label :visibility %>
    <%= f.select :visibility, Image.visibilities.keys.map { |k| [t("activerecord.enums.image.visibility.#{k}"), k] }, {} %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, Image.statuses.keys.map { |k| [t("activerecord.enums.image.status.#{k}"), k] }, {} %>
  </div>
  <br/>
  <br/>
  <%= f.submit '送信' %>
<% end %>

app/views/images/_image.html.erb
<div>
  <strong>ID:</strong> <%= image.aid %><br />
  <strong>画像名:</strong> <%= image.name %><br />
  <strong>公開状態:</strong> <%= image.visibility %><br />
  <strong>状態:</strong> <%= image.status %><br />
  <strong>variant_type:</strong>
    <%= image.variant_type.present? ? 'あり: ' + image.variant_type : 'なし' %>
    <%= button_to('削除', delete_variant_image_path(image.aid), method: :delete, data: { turbo: false }) %>
  <strong>original_ext:</strong>
    <%= image.original_ext.present? ? 'あり: ' + image.original_ext : 'なし' %>
    <%= button_to('削除', delete_original_image_path(image.aid), method: :delete, data: { turbo: false }) %>
  <strong>操作:</strong>
  <%= form_with url: create_variant_image_path(image.aid), method: :post, data: { turbo: false } do %>
    <div>
      <%= label_tag :variant_type, "variant_type" %>
      <%= select_tag :variant_type, options_for_select(['icon', 'q-icon', 'banner', 'q-banner', 'normal', 'q-normal', 'd-normal', 'emoji', 'q-emoji']) %>
    </div>
    <div>
      <%= submit_tag "送信" %>
    </div>
  <% end %>
  <%= link_to('見る', image_path(image.aid)) %>
  <%= link_to('編集', edit_image_path(image.aid)) %>
  <br />
  <%= image_tag(image.image_url, alt: "#{image.name}", style: 'width: 140px;') %>
  <hr />
</div>

app/views/images/edit.html.erb
<% provide(:title, '編集') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<%= render 'images/form', image: @image, url: image_path(@image.aid), method: :post, new: true %>

app/views/images/index.html.erb
<% provide(:title, '画像一覧') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<h1>画像一覧</h1>
<%= render partial: 'images/image', collection: @images, as: 'image' %>
<%= render 'shared/paging', pages: @total_pages, page: @page, page_to: '/images' %>

app/views/images/new.html.erb
<% provide(:title, '作成') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<%= render 'images/form', image: @image, url: images_path, method: :post, new: true %>

app/views/images/show.html.erb
<% provide(:title, '画像') %>
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>

<h1>画像</h1>
<%= image_tag(@image.image_url, alt: "#{@image.name}") %>
<hr />
<%= render 'images/image', image: @image %>

app/views/images/variants_show.html.erb
<% provide(:robots, 'false') %>
<% provide(:layout_style, '') %>
<% provide(:ga4, 'false') %>
<h1>画像バリアント確認</h1>