config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  root 'pages#index'

  # Accounts
  resources :accounts, param: :aid

  # Posts
  resources :posts, param: :aid

  # Images
  resources :images, param: :aid do
    member do
      post "create_variant" => "images#create_variant", as: "create_variant"
      delete "delete_variant" => "images#delete_variant", as: "delete_variant"
      delete "delete_original" => "images#delete_original", as: "delete_original"
    end
  end

  # Videos
  resources :videos, param: :aid do
    member do
      post "create_variant" => "videos#create_variant", as: "create_variant"
      delete "delete_variant" => "videos#delete_variant", as: "delete_variant"
      delete "delete_original" => "videos#delete_original", as: "delete_original"
    end
  end

  # Emojis
  resources :emojis, param: :aid do
    collection do
      get :picker
    end
  end

  # Reactions
  post 'reactions/react' => 'reactions#react', as: :react

  # Diffuses
  post 'diffuses/create' => 'diffuses#create', as: :diffuse
  delete 'diffuses/destroy' => 'diffuses#destroy', as: :undiffuse

  # Sessions
  get 'sessions/start'
  delete 'signout' => 'sessions#signout'
  resources :sessions, except: [:new, :create], param: :aid

  # Signup
  get 'signup' => 'signup#new'
  post 'signup' => 'signup#create'

  # OAuth
  post 'oauth/start' => 'oauth#start'
  get 'oauth/callback' => 'oauth#callback'
  post 'oauth/fetch' => 'oauth#fetch'

  # Trends
  resources :trends, only: [:index, :create]

  # Notifications
  resources :notifications, only: [:new, :create]

  # OG
  get 'og/posts/:aid' => 'og_images#post', as: :og_post
  # get 'og/accounts/:aid' => 'og_images#account', as: :og_account

  # API v1
  namespace :v1 do
    root 'pages#index'

    # Pages
    get 'start' => 'pages#start'

    # Accounts
    post 'accounts/@:name_id' => 'accounts#show', constraints: { name_id: /.*/ }
    resources :accounts, only: [], param: :aid do
      resource :follow, only: [:create, :destroy]
    end

    # Posts
    post 'posts/:aid' => 'posts#show'
    resources :posts, only: [:create, :destroy], param: :aid do
      resource :reaction, only: [:create, :destroy]
      resource :diffuse, only: [:create, :destroy]
      post 'quotes'
      post 'diffusions'
      post 'reactions'
    end

    # Emojis
    post 'emojis/groups' => 'emojis#groups_index'
    post 'emojis/groups/:group_name' => 'emojis#groups_show'
    post 'emojis/:name_id' => 'emojis#show'

    # Search
    post 'search' => 'search#index'

    # Feeds
    post 'feeds/index' => 'feeds#index'
    post 'feeds/follow' => 'feeds#follow'
    post 'feeds/current' => 'feeds#current'
    post 'feeds/account' => 'feeds#account'

    # Notifications
    post 'notifications' => 'notifications#index'
    post 'notifications/unread_count' => 'notifications#unread_count'

    # WebPush Subscriptions
    post 'webpush_subscriptions' => 'webpush_subscriptions#create'

    # Sessions
    post 'sessions/create' => 'sessions#create'
    delete 'signout' => 'sessions#signout'

    # Signup
    post 'signup' => 'signup#create'

    # Settings
    post 'settings/account' => 'settings#account'
    post 'settings/notification' => 'settings#notification'
    post 'settings/update_notification' => 'settings#update_notification'
    delete 'settings/leave' => 'settings#leave'

    # OAuth
    post 'oauth/start' => 'oauth#start'
    post 'oauth/callback' => 'oauth#callback'
    post 'oauth/fetch' => 'oauth#fetch'

    # Trends
    post 'trends' => 'trends#index'
  end

  # Others
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Errors
  match '*path', to: 'application#routing_error', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(content_for(:title) || "") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Amiverse API">
    <meta name="mobile-web-app-capable" content="yes">

    <meta name="generator" content="Amiverse API" />
    <meta name="description" content="Amiverse API" />
    <meta name="keywords" content="Amiverse API" />
    <meta name="robots" content="noindex, nofollow, noarchive" />

    <meta property="og:image" content="<%= full_url("/static_assets/images/amiverse-1.webp") %>" />
    <meta name="twitter:card" content="summary_large_image" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/favicon.ico" />

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Amiverse", root_path %></h1>
      <nav>
        <%= link_to "ホーム", root_path %> |
        <%= link_to "セッション", sessions_path %> |
        <%= link_to "画像", images_path %>
      </nav>
      <div>
        <% if @current_account %>
          サインイン中: <%= @current_account.name %> <small>@<%= @current_account.name_id %></small>
        <% else %>
          サインインしていません
        <% end %>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

    <div id="flash">
      <%= render "shared/flash" %>
    </div>

    <footer>
      <p>&copy; Amiverse</p>
    </footer>
  </body>
</html>